{% set name = "pysd" %}
{% set version = "3.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysd-{{ version }}.tar.gz
  sha256: c946c9308536e38c5d6c97375a6417efbad104f99757e878f636c6cea7afc85e

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - black
    - chardet
    - lxml
    - numpy
    - openpyxl
    - pandas
    - parsimonious <=0.9.0
    - portion
    - progressbar2
    - python >=3.7
    - regex
    - scipy
    - xarray
    - xlrd

test:
  imports:
    - pysd
    - pysd.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SDXorg/pysd
  summary: System Dynamics Modeling in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://pysd.readthedocs.io/
  dev_url: https://github.com/SDXorg/pysd

extra:
  recipe-maintainers:
    - enekomartinmartinez
    - JamesPHoughton
