{% set name = "pysd" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysd-{{ version }}.tar.gz
  sha256: 51e4e0c1c205a6324a87d7ed57b7327e40687699cd0e1973f6fef4d6962bf9f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - black
    - chardet
    - lxml
    - openpyxl
    - pandas
    - parsimonious
    - progressbar2
    - python >=3.7
    - regex
    - scipy
    - xarray
    - xlrd

test:
  imports:
    - pysd
    - pysd.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JamesPHoughton/pysd
  summary: System Dynamics Modeling in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://pysd.readthedocs.io/
  dev_url: https://github.com/JamesPHoughton/pysd

extra:
  recipe-maintainers:
    - enekomartinmartinez
    - JamesPHoughton
