{% set name = "pysd" %}
{% set version = "3.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysd-{{ version }}.tar.gz
  sha256: 4ea313222e5787cb53487fd4b12573243b383140952ab0bfddb74263cad860e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - black
    - chardet
    - lxml
    - numpy <1.24
    - openpyxl <3.1
    - pandas
    - parsimonious
    - portion
    - progressbar2
    - python >=3.7
    - regex
    - scipy
    - xarray
    - xlrd

test:
  imports:
    - pysd
    - pysd.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SDXorg/pysd
  summary: System Dynamics Modeling in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://pysd.readthedocs.io/
  dev_url: https://github.com/SDXorg/pysd

extra:
  recipe-maintainers:
    - enekomartinmartinez
    - JamesPHoughton
